export interface DatabaseSentence {
  id: number;
  text: string;
  wordCount: number;
}

export const ACADEMIC_DATABASE: DatabaseSentence[] = [
  { id: 1, text: `"No!"`, wordCount: 1 },
  { id: 2, text: `"I ask myself."`, wordCount: 3 },
  { id: 3, text: `"HR is correct."`, wordCount: 3 },
  { id: 4, text: `"Here's an illustration."`, wordCount: 3 },
  { id: 5, text: `"I'm on a X."`, wordCount: 4 },
  { id: 6, text: `"But Gus is right."`, wordCount: 4 },
  { id: 7, text: `"S are N J-s."`, wordCount: 4 },
  { id: 8, text: `"The Y is doing Z."`, wordCount: 5 },
  { id: 9, text: `"One R-s the corresponding L."`, wordCount: 5 },
  { id: 10, text: `"Z relations known through S."`, wordCount: 5 },
  { id: 11, text: `"A is conceptually articulated B."`, wordCount: 5 },
  { id: 12, text: `"Formal relationships hold between descriptions."`, wordCount: 5 },
  { id: 13, text: `"Consider the alternative mentioned earlier."`, wordCount: 5 },
  { id: 14, text: `"But this assumption is dead wrong."`, wordCount: 6 },
  { id: 15, text: `"That C is DD but non-CC."`, wordCount: 6 },
  { id: 16, text: `"The objects of C are T."`, wordCount: 6 },
  { id: 17, text: `"Rather, one C L about them."`, wordCount: 6 },
  { id: 18, text: `"It's a datum that it's bad."`, wordCount: 6 },
  { id: 19, text: `"And that is what it does."`, wordCount: 6 },
  { id: 20, text: `"The objects of evaluation are descriptions."`, wordCount: 6 },
  { id: 21, text: `"In fact, the opposite often holds."`, wordCount: 6 },
  { id: 22, text: `"You can test this for yourself."`, wordCount: 6 },
  { id: 23, text: `"A story will make this clear."`, wordCount: 7 },
  { id: 24, text: `"There are no rules without conditions."`, wordCount: 7 },
  { id: 25, text: `"One is J of V and W."`, wordCount: 8 },
  { id: 26, text: `"All CC knowledge DD but not vice versa."`, wordCount: 8 },
  { id: 27, text: `"E3 is not free from sin either."`, wordCount: 8 },
  { id: 28, text: `"Sometimes the right explanations are bad ones."`, wordCount: 8 },
  { id: 29, text: `"It B-s us F-ly while G-ing us C-ly."`, wordCount: 8 },
  { id: 30, text: `"Functional relationships hold between events or conditions."`, wordCount: 8 },
  { id: 31, text: `"All tools require some form of use."`, wordCount: 8 },
  { id: 32, text: `"Structural understanding is always understanding of relationships."`, wordCount: 8 },
  { id: 33, text: `"But not all DD C is CC C."`, wordCount: 9 },
  { id: 34, text: `"All C justified true belief but not vice versa."`, wordCount: 9 },
  { id: 35, text: `"There are infinitely many; but here are three."`, wordCount: 9 },
  { id: 36, text: `"Nonetheless, on Tuesday morning, the X is gone."`, wordCount: 9 },
  { id: 37, text: `"As it happens, you hear nothing all night."`, wordCount: 9 },
  { id: 38, text: `"What are the various possible explanations of this?"`, wordCount: 9 },
  { id: 39, text: `"A broken PP is right twice a day."`, wordCount: 9 },
  { id: 40, text: `"Solution: There is a difference between B and C."`, wordCount: 9 },
  { id: 41, text: `"Such relationships are structural, as opposed to observational."`, wordCount: 9 },
  { id: 42, text: `"Nothing can be both moving and perfectly still."`, wordCount: 9 },
  { id: 43, text: `"(An event is anything that happens in time.)"`, wordCount: 9 },
  { id: 44, text: `"and "X" to mean, respectively, "P" and "Q.""`, wordCount: 9 },
  { id: 45, text: `"In general, you are a good judge of character."`, wordCount: 10 },
  { id: 46, text: `"This is a special form of the F Paradox."`, wordCount: 10 },
  { id: 47, text: `"Solution: A technology is not supposed to B us C-ly."`, wordCount: 10 },
  { id: 48, text: `"Therefore, a plant's growth depends on its receiving water."`, wordCount: 10 },
  { id: 49, text: `"A tool's being functional depends on its being usable."`, wordCount: 10 },
  { id: 50, text: `"Why doesn't the X change under the given conditions?"`, wordCount: 10 },
  { id: 51, text: `"That reason, if it exists, must be purely theoretical."`, wordCount: 10 },
  { id: 52, text: `"It may not be contradictory in the strict sense."`, wordCount: 10 },
  { id: 53, text: `"His explanation is correct down to the last detail."`, wordCount: 10 },
  { id: 54, text: `"It's a bad explanation that turned out to be correct."`, wordCount: 10 },
  { id: 55, text: `"Equivalently, there are two kinds of J: M and N."`, wordCount: 11 },
  { id: 56, text: `"There are two broad types of relationships: formal and functional."`, wordCount: 11 },
  { id: 57, text: `"Gus and I have access to the same empirical data."`, wordCount: 11 },
  { id: 58, text: `"B answers the question: What is it objectively possible to do?"`, wordCount: 11 },
  { id: 59, text: `"Only the semantic content has been replaced with neutral placeholders."`, wordCount: 11 },
  { id: 60, text: `"In fact, each creates a whole network of deep mysteries."`, wordCount: 11 },
  { id: 61, text: `"But, of course, E3 is hands down the best explanation."`, wordCount: 11 },
  { id: 62, text: `""What on Earth does he have to do Z about?""`, wordCount: 11 },
  { id: 63, text: `"For an explanation to be good isn't for it to be correct."`, wordCount: 13 },
  { id: 64, text: `"And the second answer breaks any deadlocks created by the first."`, wordCount: 12 },
  { id: 65, text: `"A description is any statement that can be true or false."`, wordCount: 12 },
  { id: 66, text: `"Example of a functional relationship: A plant cannot grow without water."`, wordCount: 12 },
  { id: 67, text: `"Examples of structural relationships are: If A, then A or B."`, wordCount: 12 },
  { id: 68, text: `"Because, says the standard account, the key Y remained in place."`, wordCount: 12 },
  { id: 69, text: `"Setting them aside, if possible at all, would create ripple effects."`, wordCount: 12 },
  { id: 70, text: `"Those B do not only sustain the single E in question."`, wordCount: 12 },
  { id: 71, text: `"What is it that, in W∗, makes wrong explanations be good?"`, wordCount: 12 },
  { id: 72, text: `"Some relationships are known, not through direct observation, but through reasoning."`, wordCount: 12 },
  { id: 73, text: `"On Monday night, you park your X in the usual place, viz."`, wordCount: 12 },
  { id: 74, text: `"This morning he J somebody who, by coincidence, had the name K."`, wordCount: 12 },
  { id: 75, text: `"So I have my explanation: "he just came into a lot of F.""`, wordCount: 13 },
  { id: 76, text: `"The first type is structural, i.e., it holds between statements about features."`, wordCount: 13 },
  { id: 77, text: `"right in front of your house, which is in a quiet residential neighborhood."`, wordCount: 14 },
  { id: 78, text: `"This is because it is L that are R-ed, and L are true T."`, wordCount: 14 },
  { id: 79, text: `"Therefore, a shape's being a square depends on its having four equal sides."`, wordCount: 14 },
  { id: 80, text: `"So when the Y saw those D, he immediately thought of that morning's J."`, wordCount: 14 },
  { id: 81, text: `"People don't give good A to B who do not already have positive A."`, wordCount: 14 },
  { id: 82, text: `"We haven't yet refuted the A—we've only taken the first step towards doing so."`, wordCount: 15 },
  { id: 83, text: `"Taken on its own, a substitute account may describe a situation that seems coherent."`, wordCount: 15 },
  { id: 84, text: `"Consider the various B that would be altered, the C disrupted, the D prevented."`, wordCount: 15 },
  { id: 85, text: `"His job is so A, and his life must therefore be such a B."`, wordCount: 15 },
  { id: 86, text: `"(It isn't C-ed unless it's believed and it isn't believed unless it's a T.)"`, wordCount: 15 },
  { id: 87, text: `"A technology is supposed to B us but separates us into self-contained, non-interacting units."`, wordCount: 15 },
  { id: 88, text: `"CC L are necessarily C-ed through EE, and C of such L is therefore DD."`, wordCount: 15 },
  { id: 89, text: `"The existence of rules depends on the existence of conditions to which they apply."`, wordCount: 15 },
  { id: 90, text: `"You've never been as convinced of anyone's integrity as you are of Larry's."`, wordCount: 15 },
  { id: 91, text: `"His job is so A, and his life must therefore be such a B."`, wordCount: 15 },
  { id: 92, text: `"Think of the range of underlying A that would have to be set aside."`, wordCount: 16 },
  { id: 93, text: `"Indeed, a belief that he has such a gift isn't even among Gus's many delusions."`, wordCount: 16 },
  { id: 94, text: `"Thus, for an explanation to be a good one isn't for it to be correct."`, wordCount: 16 },
  { id: 95, text: `"Explanatory goodness is a relationship, not between explanations and reality, but between explanation and data."`, wordCount: 16 },
  { id: 96, text: `"In general, what is the relationship that good theories bear with respect to the data?"`, wordCount: 16 },
  { id: 97, text: `"The contents of such J-s must be converted into T if they are to be R-ed."`, wordCount: 16 },
  { id: 98, text: `"As usual, you make sure that you lock the X and turn the X-alarm on."`, wordCount: 16 },
  { id: 99, text: `"Removing them would have many other consequences—events unrelated to the specific aim of the new model."`, wordCount: 16 },
  { id: 100, text: `"1 obviously expresses a relationship; 2–4 do so less obviously, as their meanings are: 2*."`, wordCount: 16 },
  { id: 101, text: `"An object's being both moving and still depends on contradictory conditions, which cannot occur together."`, wordCount: 16 },
  { id: 102, text: `"Observational understanding can be either direct or indirect; the same is true of structural understanding."`, wordCount: 16 },
  { id: 103, text: `"Here is the fully bleached, placeholder-only version of the long Hume/induction/car-theft sample you just used."`, wordCount: 17 },
  { id: 104, text: `"The relations that hold in W∗ between theory and data coincide with those holding in W."`, wordCount: 17 },
  { id: 105, text: `"My C of that L is a conceptualization of my J of that state of affairs."`, wordCount: 17 },
  { id: 106, text: `"I notice that you look FF and on that basis C that you didn't get enough GG."`, wordCount: 17 },
  { id: 107, text: `"In other words, Z relations can only be C-ed BB; and C of them is therefore BB."`, wordCount: 17 },
  { id: 108, text: `"That's why the ones that are wrong in W∗ are no less good on that account."`, wordCount: 18 },
  { id: 109, text: `"To R some X or Y x is to R why it is a L that x occurred."`, wordCount: 18 },
  { id: 110, text: `"The second is operational, i.e., it holds between things in the world as they act or change."`, wordCount: 18 },
  { id: 111, text: `"Something is not evaluated unless it is described, and it is not described unless it can be stated."`, wordCount: 18 },
  { id: 112, text: `"A continuation of the earlier case will make it clear what this means and why it matters."`, wordCount: 18 },
  { id: 113, text: `"And for reasons soon to be made clear, no such purely theoretical reason can justify accepting it."`, wordCount: 18 },
  { id: 114, text: `"The purpose of explanation is to minimize the breadth and depth of what must be taken for granted."`, wordCount: 19 },
  { id: 115, text: `"It is not at all clear that, once the relevant details are considered, the replacement is even logically possible."`, wordCount: 19 },
  { id: 116, text: `"But that alone is not enough for it to serve as a viable model of the relevant information."`, wordCount: 19 },
  { id: 117, text: `"But then I remember that, just a minute ago, a C gave him fifty D as an E."`, wordCount: 19 },
  { id: 118, text: `"Unless you think that nature is uniform, you have no right to expect that connection to continue to hold."`, wordCount: 20 },
  { id: 119, text: `"One can notice non-descriptions — sounds, objects, movements — but in the relevant sense one evaluates descriptions of them."`, wordCount: 20 },
  { id: 120, text: `"Hume's argument assumes that it is only through prediction by enumeration that the past is any guide to the future."`, wordCount: 21 },
  { id: 121, text: `"Each of E1 and E2 replaces the mystery of how your X could be noiselessly stolen with a far greater mystery."`, wordCount: 21 },
  { id: 122, text: `"One can be J of non-T, e.g. UU, VV, WW, but one does not in the relevant sense C them."`, wordCount: 21 },
  { id: 123, text: `"The cost of that account—meaning what new puzzles it creates—is vastly greater than its value—meaning what old puzzles it removes."`, wordCount: 21 },
  { id: 124, text: `"If there is reason to think even one such account exists, it is not because it has ever been produced."`, wordCount: 21 },
  { id: 125, text: `"C answers the question: What do my limited resources of D, E and B make it incumbent on me to do?"`, wordCount: 21 },
  { id: 126, text: `"In order for me to C that my D are uncomfortably E, I need to have the concepts F, G, H, etc."`, wordCount: 22 },
  { id: 127, text: `"(Gus hasn't read the Y's diary; he doesn't know the Y any more intimately than I do; and so on.)"`, wordCount: 22 },
  { id: 128, text: `"A HH is given by a T that, if true, describes some relatively comprehensive fact about the structure of the II."`, wordCount: 22 },
  { id: 129, text: `"But, the skeptic will counter, perhaps we can discard that account; perhaps there's an alternative that fits the Z equally well."`, wordCount: 22 },
  { id: 130, text: `"But here is the very different explanation tendered by my seatmate Gus, who, in addition to being G, is also completely H."`, wordCount: 23 },
  { id: 131, text: `"Nor does he have any good reason; even if, for argumentative purposes, we grant him his delusions; to believe what he believes."`, wordCount: 23 },
  { id: 132, text: `"This circle can be broken by C who mass-produce E, but there is no real way for other C to break it."`, wordCount: 23 },
  { id: 133, text: `"Every single punctuation mark, asterisk, parenthesis, em-dash, list structure, sentence length, and discourse rhythm is 100 % identical to the original."`, wordCount: 23 },
  { id: 134, text: `"But there is a further difficulty for this—or, by a similar line of thought, for any non-standard—replacement of the conventional view."`, wordCount: 23 },
  { id: 135, text: `"The J was a particularly enjoyable one; the Y is remembering the fun he had, and that's why he's doing Z."`, wordCount: 24 },
  { id: 136, text: `"Given that it turned out to be correct, should we say that, despite first appearances, Gus's explanation is not a bad one?"`, wordCount: 24 },
  { id: 137, text: `"If you C it, then (i) You believe it, (ii) It is true, and (iii) Your reasons for believing it are legitimate."`, wordCount: 24 },
  { id: 138, text: `"I do not need to have these concepts; or, arguably, any concepts; to be J of the uncomfortable K in my D."`, wordCount: 24 },
  { id: 139, text: `"Z relations can be C-ed only through one's senses (through sight, touch, etc.) and through real-time J of one's own AA processes."`, wordCount: 24 },
  { id: 140, text: `"On the contrary, it is supposed to B us in such a way that we can D without having to E C-ly."`, wordCount: 24 },
  { id: 141, text: `"The person who never B from C may in some contexts claim that a D is worthless, but he is unlikely to act accordingly."`, wordCount: 25 },
  { id: 142, text: `"Analysis: This is a veridical paradox, in the sense that it describes an actual vicious circle and does not represent a logical blunder."`, wordCount: 25 },
  { id: 143, text: `"Given where your home is in relation to where the X is parked, you'd almost certainly hear the X-alarm if it went off."`, wordCount: 25 },
  { id: 144, text: `"At the same time, given only that it's true and that you are justified in believing it, it doesn't follow that you C it."`, wordCount: 27 },
  { id: 145, text: `"An independent C is by definition one who does not have a D apparatus behind him, and such a C depends on uncoerced positive A."`, wordCount: 27 },
  { id: 146, text: `"My C that there is a P in front of me is a case of M-J, as is my C that my D are uncomfortably E."`, wordCount: 27 },
  { id: 147, text: `"The more a proposed theory requires you to say: "things just happen that way; there's no explaining it," the less successful an explanation it is."`, wordCount: 27 },
  { id: 148, text: `"But if, in order to deal with this, you suppose that nature is uniform, then you're caught in the vicious circle that I described."`, wordCount: 27 },
  { id: 149, text: `"This belief becomes rational when, and only when, you have reason to believe that a X-outcome is favored by the structures involved in the setup."`, wordCount: 27 },
  { id: 150, text: `"Without being morose or censorious, he exudes a decency and centeredness that you've never even seen in a head of state, let alone an X-thief."`, wordCount: 27 },
  { id: 151, text: `"In fact, it takes up so much space on the device that the remaining spaces are too small for the item to fit into them."`, wordCount: 27 },
  { id: 152, text: `"It assumes that, so far as we have any reason to believe that future As will be Bs, it is that past As have been Bs."`, wordCount: 28 },
  { id: 153, text: `"But in making an inductive inference, one doesn't assume UP and, moreover, one doesn't assume anything that, like UP, can be known only on inductive grounds."`, wordCount: 28 },
  { id: 154, text: `"You also put an almost, but not quite, indestructible device (popularly known as "The Club") on the steering-wheel that locks it into place, making the X undriveable."`, wordCount: 28 },
  { id: 155, text: `"In any case, that's what you believe and that's what others tell you; and your judgments about people have generally been borne out by subsequent events."`, wordCount: 28 },
  { id: 156, text: `"It would be difficult to devise an account inconsistent with the conventional one that, while still matching the relevant evidence, is equally efficient in explanatory terms."`, wordCount: 28 },
  { id: 157, text: `"And Gus doesn't have some sort of psychic gift that would give him access to otherwise unknowable facts about the Y's mind that would legitimize his explanation."`, wordCount: 29 },
  { id: 158, text: `"The solution: Taken in isolation, a given C can be interpreted as a C of compliance with any given one of a plurality of incompatible B-s."`, wordCount: 29 },
  { id: 159, text: `"If you say "X" when I ask you "what is Y?", I cannot on the basis alone rule out the possibility that you took "what is Y?""`, wordCount: 29 },
  { id: 160, text: `"Example of a formal relationship: The description that a shape is a square cannot be true unless the description that it has four equal sides is true."`, wordCount: 29 },
  { id: 161, text: `"But, I would respond, even granting for argument's sake that such an alternative exists, it doesn't follow that it avoids more gaps than the one it replaces."`, wordCount: 29 },
  { id: 162, text: `"And that belief, in its turn, is rational if you know that circumstances at all like the following obtain: *The objects are Y-attracted to the X-spot."`, wordCount: 29 },
  { id: 163, text: `"Given that there is almost always a more A course of action, the ability to identify A courses of action may lead to a failure to act."`, wordCount: 29 },
  { id: 164, text: `"My O perception of the P in front of me is a case of N J, as is my J of the K of my D."`, wordCount: 30 },
  { id: 165, text: `"For you to be en rapport with those RR is for you to be linked to them by structures that are SS-transmissive, as opposed to merely TT-generative."`, wordCount: 30 },
  { id: 166, text: `"Explanation: G want others to share their H, and if that involves hyper-valuing the very people or institutions that put them in that H, then so be it."`, wordCount: 30 },
  { id: 167, text: `"But people are extremely reluctant to give good A to C who are not popular already or who do not have the weight of some institution behind them."`, wordCount: 31 },
  { id: 168, text: `"It doesn't follow that it is comparable from a trade-off standpoint to the original—that it reduces as many issues as the old view while introducing no more new ones."`, wordCount: 31 },
  { id: 169, text: `"What one assumes is that explanations are supposed to eliminate causal anomalies—that they are supposed to reduce the number of them and to limit the scope of those that aren't eliminated."`, wordCount: 32 },
  { id: 170, text: `"(E2) As you were sleeping, the laws of physics changed in such a way that hitherto noisy processes (e.g., those that occur when X-alarms go off) are no longer noisy."`, wordCount: 32 },
  { id: 171, text: `"When he comes across someone without a D who is trying to make something of himself, he is likely to pounce on that person, claiming he is an un-E F."`, wordCount: 33 },
  { id: 172, text: `"(E1) Using his or her super powers to bypass the security measures you took, some superhero-like creature made off with the X, making little or no noise and leaving few or no clues."`, wordCount: 34 },
  { id: 173, text: `"But a short extension of our story illustrates the even stronger principle that for an explanation to be a good one isn't even for it to be likely to be correct."`, wordCount: 34 },
  { id: 174, text: `"When would it become rational to believe that, next time, you're more likely than not to get this as opposed to that outcome—that, for example, you're especially likely to get a X?"`, wordCount: 35 },
  { id: 175, text: `"What one assumes, then, is that it is inherent in the very concept of explanation that, other things being equal, T1 is a better explanation than T2 if T1 generates fewer anomalies than T2."`, wordCount: 37 },
  { id: 176, text: `"Any given A complies with many different B-s, and there is therefore no good reason to say of a given C that it is a C of following this as opposed to that B."`, wordCount: 37 },
  { id: 177, text: `"Your belief would have been C had you acquired it by virtue of being en rapport with the relevant RR; and the reason it wasn't C is that it was not so acquired."`, wordCount: 37 },
  { id: 178, text: `"People who are at the bottom of a A are far less likely to spurn that A than they are to use it against people who are trying to climb the ranks of that A."`, wordCount: 38 },
  { id: 179, text: `"And you know that you didn't sleep any more deeply than usual—that, for example, you weren't in a particularly deep drug-induced slumber—and, in general, that you weren't made less sensitive to noise than you usually are."`, wordCount: 39 },
  { id: 180, text: `"If your belief that it's QQ is based on the read-out of a broken PP, it isn't C, even if that PP happens to be right and, in addition, you C it to be relatively reliable."`, wordCount: 39 },
  { id: 181, text: `"Let W be the real world and let W∗ be a hypothetical world where we have the exact same experiences that we have in W, but in which the Guss of the world are always right."`, wordCount: 40 },
  { id: 182, text: `"But if that is what you meant, there will be independent evidence for it, meaning that there will be some reason independently of this context to believe that you take those symbols to have those meanings."`, wordCount: 40 },
  { id: 183, text: `"… (the rest of the original text continues in exactly the same bleached form, but I'll stop here to keep it manageable; let me know if you need the remaining ~60 % of it bleached as well)"`, wordCount: 40 },
  { id: 184, text: `"(E3) Your good friend Larry—who, despite his numerous convictions for X-theft, simply radiates trustworthiness and decency, and to whom, without so much as a touch of anxiety, you therefore gave copies of all your keys—made off with the X."`, wordCount: 41 },
  { id: 185, text: `"In W∗, it's because P is personally Q R to millions of S that they suddenly appear in T round the globe; it's because the U is personally V W that they disappear from under X; and so on."`, wordCount: 41 },
  { id: 186, text: `"If you know on independent grounds that there is no such mechanism, no run of As that are Bs, no matter how long, gives you a reason to think that the next A will be a B."`, wordCount: 41 },
  { id: 187, text: `"And to the extent that a long run of X-outcomes doesn't give you such a reason, you are irrational to believe that you're any more (or any less) likely to get a X than you are any other outcome."`, wordCount: 42 },
  { id: 188, text: `"You are rational to believe that you'll continue to get Xs to the extent that your having thus far gotten multiple Xs in a row gives you reason to believe there to be some underlying structure favoring that outcome."`, wordCount: 43 },
  { id: 189, text: `"And there is no assurance that these other consequences would be compatible, even in a purely formal sense, with the data the new account is supposed to capture as well as the conventional one it seeks to replace."`, wordCount: 43 },
  { id: 190, text: `"The best explanation of the fact that all known As are Bs is that, thanks to some mechanism or, in any case, principled connection of some kind or other, a thing's being an A disposes it to be a B."`, wordCount: 44 },
  { id: 191, text: `"The B could defend his view against what we've said thus far by saying the following: Suppose that, to explain why all Cs thus far known are Ds, you posit some underlying structure or law that disposes Cs to be Ds."`, wordCount: 44 },
  { id: 192, text: `"One is indeed caught in a vicious circle if, in order to show the legitimacy of inductive inference, one assumes UP; and the reason is that, just as B says, UP can be known, if at all, only on inductive grounds."`, wordCount: 45 },
  { id: 193, text: `"The fact that past As were Bs, is not, in and of itself, reason to hold that future As will be Bs; it is such a reason only to the extent that it suggests some mechanism that disposes As to be Bs."`, wordCount: 46 },
  { id: 194, text: `"So any putative case of following a given B might equally reasonably be seen as a case of following some other, incompatible B, and there is therefore no good reason to regard any C as a case of following any given B."`, wordCount: 48 },
  { id: 195, text: `"Thus, any case of prediction by enumeration that isn't an instance of the gambler's fallacy involves the positing some mechanism or law that, were it to exist, would explain a certain pattern—it involves, in other words, a case of inference to the best explanation."`, wordCount: 48 },
  { id: 196, text: `"So, no matter how many consecutive Xs you get, if you know with certainty that there is no underlying structure that would favor such an outcome, then you have no more reason to expect a X than you do a Y or a Z."`, wordCount: 48 },
  { id: 197, text: `"Put pedantically, it is only insofar as you have reason to believe in such a structure that you have reason to expect something that has the property of being an item produced by you to have the property of landing in the X-spot."`, wordCount: 48 },
  { id: 198, text: `"*On any given occasion, you have an unconscious intention to produce a X (even though you have no conscious intention of doing this), and you're such a talented operator that, if you can produce a X if it is your (subconscious) intention to do so."`, wordCount: 52 },
  { id: 199, text: `"Your knowing of many As that are Bs and of none that are not doesn't necessarily give you any reason to believe that the next A you encounter will be a B; it gives you such a reason only insofar as it gives you a reason to believe in some structure or mechanism that disposes As to be Bs."`, wordCount: 65 },
  { id: 200, text: `"CC C is either (i) C of such a HH (e.g. your C of JJ) or (ii) C that is derived from C of such a HH (e.g. your C that, the laws of KK being what they are and LL x's state of MM being what it is, x will NN with OO y in approximately two hours)."`, wordCount: 71 },
];

export const PERSONAL_DATABASE: DatabaseSentence[] = [
  { id: 1, text: "My A.", wordCount: 2 },
  { id: 2, text: "It is A work; but impossible to B.", wordCount: 8 },
  { id: 3, text: "Trying to cope with that F is really A.", wordCount: 9 },
  { id: 4, text: "Trying to handle that F is completely A.", wordCount: 8 },
  { id: 5, text: "But you are very A that you were B now.", wordCount: 10 },
  { id: 6, text: "But you're honestly A to be A right now.", wordCount: 9 },
  { id: 7, text: "Getting handed a A set of A wasn't what you would've A.", wordCount: 12 },
  { id: 8, text: "Having been given a very A set of A may not be your first A.", wordCount: 14 },
  { id: 9, text: "Try and keep A A in a A.", wordCount: 8 },
  { id: 10, text: "Access to your A A and A limited.", wordCount: 7 },
  { id: 11, text: "The A must be A in A to prevent any A of said A.", wordCount: 13 },
  { id: 12, text: "Only put up A of them A and no one A.", wordCount: 10 },
  { id: 13, text: "It might be worth installing a A A A so they have A to an A where they can A A.", wordCount: 18 },
  { id: 14, text: "There's probably A A away from them.", wordCount: 6 },
  { id: 15, text: "The A A can be so A they will A you in the A in case you don't A them.", wordCount: 18 },
  { id: 16, text: "It's probably A to get a A with no A with the A A.", wordCount: 13 },
  { id: 17, text: "So WFH can be a A.", wordCount: 6 },
  { id: 18, text: "Or keep a A A A where you can A for every A A out of it without being A.", wordCount: 18 },
  { id: 19, text: "A A provide them with a A so they can A in on your A A.", wordCount: 15 },
  { id: 20, text: "Always A if the A becomes non-A A that the A is the A of your A forever.", wordCount: 16 },
  { id: 21, text: "Of course you can but think of it like A A.", wordCount: 10 },
  { id: 22, text: "Especially A it will be your A A A by them.", wordCount: 10 },
  { id: 23, text: "Or find an A S A-A A or if there isn't one start one.", wordCount: 13 },
  { id: 24, text: "Or A down an A A-A A; if none A, start one.", wordCount: 11 },
  { id: 25, text: "S is a A, A A that you can use to A a A-A A.", wordCount: 14 },
  { id: 26, text: "That A is A-out A and A-changing; A of A who use its A every A A the A completely and A up with A, A, F-free A.", wordCount: 26 },
  { id: 27, text: "Many A who use S A on a A A lose the A and A A A F-free A.", wordCount: 18 },
  { id: 28, text: "As some A put it, you literally are like A on C.", wordCount: 11 },
  { id: 29, text: "It can be the most D of E but also packed with F and you have to A so A not to A a G or total H.", wordCount: 24 },
  { id: 30, text: "The A A are I; what's coming next?", wordCount: 8 },
  { id: 31, text: "Will they just J or do you find them K?", wordCount: 9 },
  { id: 32, text: "Will the L A because they've been M and N?", wordCount: 9 },
  { id: 33, text: "Will the O start A the P, just waiting for you to Q once.", wordCount: 12 },
  { id: 34, text: "The A everyone A about is A R-A S, but A those S A like A for A.", wordCount: 15 },
  { id: 35, text: "But then again it isn't all T.", wordCount: 7 },
  { id: 36, text: "They can be insanely U and V and the A A are as A as it gets for A.", wordCount: 17 },
  { id: 37, text: "Not every A is A; some A it A pretty A until A W or one A X A gets A.", wordCount: 18 },
  { id: 38, text: "I think it's A to see that yeah, you do A Y and Z for A who AA you.", wordCount: 17 },
  { id: 39, text: "But anyone who A through that is A A, A BB.", wordCount: 11 },
  { id: 40, text: "Most of the A that A with B A are how to A with the C of D A caused by E.", wordCount: 20 },
  { id: 41, text: "Most of the A A with B A A are how to A with the C of D A A by E.", wordCount: 20 },
  { id: 42, text: "They get stuck in a A of F because their A A them to A A that are not in A with their A about who they A.", wordCount: 26 },
  { id: 43, text: "They get A in a A of F because those A A them to A A that don't A who they think they A.", wordCount: 23 },
  { id: 44, text: "If you had a G or H A, you will at some A need to A those A A with the A of a I.", wordCount: 23 },
  { id: 45, text: "If you grew up G or H, at some A you'll have to A-A those A A with A A to A you.", wordCount: 21 },
  { id: 46, text: "A have always had B, but in the last A or A A A figured out a A to A A with B how to A their A.", wordCount: 28 },
  { id: 47, text: "A have always had B, but only in the last A-A A did someone finally A how to A them to A their A.", wordCount: 24 },
  { id: 48, text: "I know S is A and may not be A to you, but if you can't get into a A A A the S A and A to get a A A to A you A A it.", wordCount: 40 },
  { id: 49, text: "I know the A A A a A and might not even be A where you A, but if you can't get in, just A the A and A a A or A A into A it with you.", wordCount: 38 },
  { id: 50, text: "But A a A A to J is very A, and it will A you a A and a A of A that very A A A.", wordCount: 25 },
  { id: 51, text: "But a A A around J A up A A A and A you a A of A and A A almost A A ever A.", wordCount: 23 },
  { id: 52, text: "If they're A A in their own A then there's every A a A A of A A out and the A A can A in so A plenty of A to A through a A that has A A.", wordCount: 40 },
  { id: 53, text: "The A sounds A and that's pretty much what you A up to.", wordCount: 12 },
  { id: 54, text: "So yeah it doesn't A A but if you A for the most A at least you A what to A.", wordCount: 18 },
  { id: 55, text: "If however you want to A a A where you A and A your A A then don't even A about A in with a A.", wordCount: 23 },
  { id: 56, text: "It A some A, but I think the first A is to A that you were A so you can now be A.", wordCount: 21 },
  { id: 57, text: "And sometimes you need to A yourself.", wordCount: 6 },
  { id: 58, text: "A new A, A new A, A new A.", wordCount: 9 },
  { id: 59, text: "And those A, A and A that A A A A, are probably A.", wordCount: 12 },
  { id: 60, text: "I first A to A that because I A A and A, I have to A A and A with more A A and more A.", wordCount: 23 },
  { id: 61, text: "It becomes A with A and my A toward A, A but most A SELF are becoming more A.", wordCount: 15 },
  { id: 62, text: "For me it is not who I A, but who I want to A and what I A to A.", wordCount: 18 },
  { id: 63, text: "But rather than A of the J A as A way A A and having to A for A just to get to the A A, it can be A to A go of the A of A like A A and A that yours may be a A that will have its A A on J.", wordCount: 56 },
  { id: 64, text: "But instead of A the J A as A A behind A A and A for A just to A the A A, it's often A to A the A of A like A A and A that your A might A on J.", wordCount: 44 },
  { id: 65, text: "A yourself in J through K, A in L, M or N A, O A, P, Q or R can A for a very A A through A even if you never get \"A\" enough to A A on yourself.", wordCount: 38 },
  { id: 66, text: "A yourself into J through K, A out on L, M A, N-A, O, P, Q or A A can A into a very A A to A even if you never get \"A\" enough to A A on yourself.", wordCount: 38 },
];

export type StyleMode = 'academic' | 'personal' | 'custom';

export function getDatabase(mode: StyleMode): DatabaseSentence[] {
  switch (mode) {
    case 'academic':
      return ACADEMIC_DATABASE;
    case 'personal':
      return PERSONAL_DATABASE;
    default:
      return [];
  }
}
