import type { WritingSample } from "@shared/schema";

export const writingSamples: WritingSample[] = [
  {
    id: "formal-functional-relationships",
    name: "Formal and Functional Relationships",
    preview: "There are two broad types of relationships: formal and functional...",
    content: "There are two broad types of relationships: formal and functional. Formal relationships hold between descriptions. A description is any statement that can be true or false. Example of a formal relationship: The description that a shape is a square cannot be true unless the description that it has four equal sides is true. Therefore, a shape's being a square depends on its having four equal sides. Functional relationships hold between events or conditions. (An event is anything that happens in time.) Example of a functional relationship: A plant cannot grow without water. Therefore, a plant's growth depends on its receiving water. The first type is structural, i.e., it holds between statements about features. The second is operational, i.e., it holds between things in the world as they act or change. Descriptions as objects of consideration. The objects of evaluation are descriptions. Something is not evaluated unless it is described, and it is not described unless it can be stated. One can notice non-descriptions — sounds, objects, movements — but in the relevant sense one evaluates descriptions of them. Relationships not known through direct observation. Some relationships are known, not through direct observation, but through reasoning. Such relationships are structural, as opposed to observational. Examples of structural relationships are: If A, then A or B. All tools require some form of use. Nothing can be both moving and perfectly still. There are no rules without conditions. 1 obviously expresses a relationship; 2–4 do so less obviously, as their meanings are: 2*. A tool's being functional depends on its being usable. 3*. An object's being both moving and still depends on contradictory conditions, which cannot occur together. 4*. The existence of rules depends on the existence of conditions to which they apply. Structural truth and structural understanding. Structural understanding is always understanding of relationships. Observational understa...",
    category: "Content-Neutral"
  },
  {
    id: "rational-belief-structure",
    name: "Rational Belief and Underlying Structure (Placeholder)",
    preview: "When would it become rational to believe that, next time...",
    content: "When would it become rational to believe that, next time, you're more likely than not to get this as opposed to that outcome—that, for example, you're especially likely to get a X? This belief becomes rational when, and only when, you have reason to believe that a X-outcome is favored by the structures involved in the setup. And that belief, in its turn, is rational if you know that circumstances at all like the following obtain: *The objects are Y-attracted to the X-spot. *On any given occasion, you have an unconscious intention to produce a X (even though you have no conscious intention of doing this), and you're such a talented operator that, if you can produce a X if it is your (subconscious) intention to do so. *The X-spot is much bigger than any of the other spots. In fact, it takes up so much space on the device that the remaining spaces are too small for the item to fit into them. You are rational to believe that you'll continue to get Xs to the extent that your having thus far gotten multiple Xs in a row gives you reason to believe there to be some underlying structure favoring that outcome. And to the extent that a long run of X-outcomes doesn't give you such a reason, you are irrational to believe that you're any more (or any less) likely to get a X than you are any other outcome. So, no matter how many consecutive Xs you get, if you know with certainty that there is no underlying structure that would favor such an outcome, then you have no more reason to expect a X than you do a Y or a Z. Put pedantically, it is only insofar as you have reason to believe in such a structure that you have reason to expect something that has the property of being an item produced by you to have the property of landing in the X-spot. Your knowing of many As that are Bs and of none that are not doesn't necessarily give you any reason to believe that the next A you encounter will be a B; it gives you such a reason only insofar as it gives you a reason to believe...",
    category: "Epistemology"
  },
  {
    id: "hume-induction-explanation",
    name: "Hume, Induction, and the Logic of Explanation (Placeholder)",
    preview: "We haven't yet refuted the A—we've only taken the first step...",
    content: "We haven't yet refuted the A—we've only taken the first step towards doing so. The B could defend his view against what we've said thus far by saying the following: Suppose that, to explain why all Cs thus far known are Ds, you posit some underlying structure or law that disposes Cs to be Ds. Unless you think that nature is uniform, you have no right to expect that connection to continue to hold. But if, in order to deal with this, you suppose that nature is uniform, then you're caught in the vicious circle that I described. HR is correct. One is indeed caught in a vicious circle if, in order to show the legitimacy of inductive inference, one assumes UP; and the reason is that, just as B says, UP can be known, if at all, only on inductive grounds. But in making an inductive inference, one doesn't assume UP and, moreover, one doesn't assume anything that, like UP, can be known only on inductive grounds. What one assumes is that explanations are supposed to eliminate causal anomalies—that they are supposed to reduce the number of them and to limit the scope of those that aren't eliminated. What one assumes, then, is that it is inherent in the very concept of explanation that, other things being equal, T1 is a better explanation than T2 if T1 generates fewer anomalies than T2. The purpose of explanation is to minimize the breadth and depth of what must be taken for granted. The more a proposed theory requires you to say: \"things just happen that way; there's no explaining it,\" the less successful an explanation it is. Here's an illustration. On Monday night, you park your X in the usual place, viz. right in front of your house, which is in a quiet residential neighborhood. As usual, you make sure that you lock the X and turn the X-alarm on. You also put an almost, but not quite, indestructible device (popularly known as \"The Club\") on the steering-wheel that locks it into place, making the X undriveable. Given where your home is in relation to where t...",
    category: "Epistemology"
  },
  {
    id: "explanation-goodness-correctness",
    name: "Explanatory Goodness vs. Correctness (Placeholder)",
    preview: "For an explanation to be good isn't for it to be correct...",
    content: "For an explanation to be good isn't for it to be correct. Sometimes the right explanations are bad ones. A story will make this clear. I'm on a X. The Y is doing Z. A mystery! \"What on Earth does he have to do Z about?\" I ask myself. His job is so A, and his life must therefore be such a B. But then I remember that, just a minute ago, a C gave him fifty D as an E. So I have my explanation: \"he just came into a lot of F.\" But here is the very different explanation tendered by my seatmate Gus, who, in addition to being G, is also completely H. \"The Y is a I. This morning he J somebody who, by coincidence, had the name K. K (the L, not the M) is on the D. So when the Y saw those D, he immediately thought of that morning's J. The J was a particularly enjoyable one; the Y is remembering the fun he had, and that's why he's doing Z.\" Gus and I have access to the same empirical data. (Gus hasn't read the Y's diary; he doesn't know the Y any more intimately than I do; and so on.) And Gus doesn't have some sort of psychic gift that would give him access to otherwise unknowable facts about the Y's mind that would legitimize his explanation. Indeed, a belief that he has such a gift isn't even among Gus's many delusions. Nor does he have any good reason; even if, for argumentative purposes, we grant him his delusions; to believe what he believes. But Gus is right. His explanation is correct down to the last detail. Given that it turned out to be correct, should we say that, despite first appearances, Gus's explanation is not a bad one? No! It's a datum that it's bad. It's a bad explanation that turned out to be correct. Thus, for an explanation to be a good one isn't for it to be correct. But a short extension of our story illustrates the even stronger principle that for an explanation to be a good one isn't even for it to be likely to be correct. Let W be the real world and let W∗ be a hypothetical world where we have the exact same experiences that we have ...",
    category: "Epistemology"
  },
  {
    id: "knowledge-awareness-distinction",
    name: "Knowledge vs. Awareness (Placeholder)",
    preview: "A is conceptually articulated B...",
    content: "A is conceptually articulated B. In order for me to C that my D are uncomfortably E, I need to have the concepts F, G, H, etc. I do not need to have these concepts; or, arguably, any concepts; to be J of the uncomfortable K in my D. My C of that L is a conceptualization of my J of that state of affairs. Equivalently, there are two kinds of J: M and N. My O perception of the P in front of me is a case of N J, as is my J of the K of my D. My C that there is a P in front of me is a case of M-J, as is my C that my D are uncomfortably E. L, not Q, the objects of R. S are N J-s. The contents of such J-s must be converted into T if they are to be R-ed. This is because it is L that are R-ed, and L are true T. \"But don't we R U?\" it will be objected. \"Don't we R V and W?\" To R some X or Y x is to R why it is a L that x occurred. One is J of V and W. One R-s the corresponding L. Z relations known through S. Z relations can be C-ed only through one's senses (through sight, touch, etc.) and through real-time J of one's own AA processes. In other words, Z relations can only be C-ed BB; and C of them is therefore BB. All CC knowledge DD but not vice versa. CC L are necessarily C-ed through EE, and C of such L is therefore DD. But not all DD C is CC C. I notice that you look FF and on that basis C that you didn't get enough GG. That C is DD but non-CC. HH and CC C. A HH is given by a T that, if true, describes some relatively comprehensive fact about the structure of the II. CC C is either (i) C of such a HH (e.g. your C of JJ) or (ii) C that is derived from C of such a HH (e.g. your C that, the laws of KK being what they are and LL x's state of MM being what it is, x will NN with OO y in approximately two hours). All C justified true belief but not vice versa. If you C it, then (i) You believe it, (ii) It is true, and (iii) Your reasons for believing it are legitimate. At the same time, given only that it's true and that you are justified in believing it, it doe...",
    category: "Epistemology"
  },
  {
    id: "alternative-accounts-explanatory-efficiency",
    name: "Alternative Accounts and Explanatory Efficiency (Placeholder)",
    preview: "A continuation of the earlier case will make it clear what this means...",
    content: "A continuation of the earlier case will make it clear what this means and why it matters. Why doesn't the X change under the given conditions? Because, says the standard account, the key Y remained in place. But, the skeptic will counter, perhaps we can discard that account; perhaps there's an alternative that fits the Z equally well. But, I would respond, even granting for argument's sake that such an alternative exists, it doesn't follow that it avoids more gaps than the one it replaces. It doesn't follow that it is comparable from a trade-off standpoint to the original—that it reduces as many issues as the old view while introducing no more new ones. In fact, the opposite often holds. Consider the alternative mentioned earlier. The cost of that account—meaning what new puzzles it creates—is vastly greater than its value—meaning what old puzzles it removes. It would be difficult to devise an account inconsistent with the conventional one that, while still matching the relevant evidence, is equally efficient in explanatory terms. You can test this for yourself. If there is reason to think even one such account exists, it is not because it has ever been produced. That reason, if it exists, must be purely theoretical. And for reasons soon to be made clear, no such purely theoretical reason can justify accepting it. But there is a further difficulty for this—or, by a similar line of thought, for any non-standard—replacement of the conventional view. It is not at all clear that, once the relevant details are considered, the replacement is even logically possible. Taken on its own, a substitute account may describe a situation that seems coherent. It may not be contradictory in the strict sense. But that alone is not enough for it to serve as a viable model of the relevant information. Think of the range of underlying A that would have to be set aside. Setting them aside, if possible at all, would create ripple effects. Consider the various B that would be...",
    category: "Content-Neutral"
  }
];

export function getSamplesByCategory(category: string): WritingSample[] {
  return writingSamples.filter(sample => sample.category === category);
}

export function getCategories(): string[] {
  return [...new Set(writingSamples.map(sample => sample.category))].sort();
}

export function getCategoryCounts(): Record<string, number> {
  return writingSamples.reduce((acc, sample) => {
    acc[sample.category] = (acc[sample.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
}

export const paradoxSamples = getSamplesByCategory("Paradoxes");
